---
# tasks file for apt-mirrors

#- name: "[APT-mirrors] Add i386 architectures"
#  become: true
#  command:
#    cmd: dpkg --add-architecture i386

# add local mirrors from :
# https://www.parrotsec.org/docs/mirrors/mirrors-list/#emea-europe-middle-east-and-africa
- name: "[APT-mirrors] add repo mirrors"
  become: true
  ansible.builtin.copy:
    src: apt-parrot-mirrors.list
    dest: /etc/apt/sources.list.d/parrot-mirrors.list
    owner: root
    group: root
    mode: "0644"
  tags:
  - apt

