---
# tasks file for baseline

- name: Baseline
  include_tasks: sys-locale.yml
  when: ansible_os_family == "Parrot OS"
        
- name: Baseline
  include_tasks: apt-mirrors.yml
  when: ansible_os_family == "Parrot OS"

- name: Baseline
  include_tasks: apt-update.yml

- name: Baseline
  include_tasks: sys-mlocate.yml

- name: Baseline
  include_tasks: sys-unattended-upgrades.yml

- name: baseline
  include_tasks: apt-installs.yml
