---
# tasks file for devel


  
- name: "Installing Packages"
  package:
    name:
      - mingw-w64
    state: latest
  become: true

- ansible.builtin.include_tasks: git.yaml
- ansible.builtin.include_tasks: vim.yaml
- ansible.builtin.include_tasks: vscode.yaml
