---

- name: "ssh > create user ssh directory"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0740'

- name: "ssh > ssh config file"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/sshconfig"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: '0440'

- name: "Update user ssh config"
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    insertafter : EOF
    # append_newline: true  # added in ansible-core 2.16
    # prepend_newline: true   # added in ansible-core 2.16
    marker: "# -=-=- {mark} ANSIBLE MANAGED BLOCK -=-=-"
    block: "{{ sshconfig_custom }}"
