---

- name: "clean directories"
  ansible.builtin.file:
    path: "{{ tools_root_path }}/chisel"
    state: absent
  become: true

- name: "create directories"
  ansible.builtin.file:
    path: "{{ tools_root_path }}/chisel"
    state: directory
    mode: '0755'
  become: true

- name: Get chisel latest tag
  uri:
    url: https://api.github.com/repos/jpillora/chisel/releases/latest
    return_content: true
  register: chisel_release

- name: Latest release
  ansible.builtin.debug:
    msg: "Chisel version: {{ chisel_release.json.name }}"


# --- Linux ---

- name: Select chisel Linux artifact
  set_fact:
    chisel_release_linux: "{{ (chisel_release.json.assets | selectattr('name', 'match', '.*_linux_amd64.gz' ))[0] }}"

- name: Download Linux artifact
  ansible.builtin.get_url:
    url:  "{{ chisel_release_linux.browser_download_url }}"
    dest: "{{ tools_root_path }}/chisel/{{ chisel_release_linux.name }}"
  become: true

# unarchive do not support *.gz
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html#notes
- name: Extract content
  ansible.builtin.command:
    cmd: "gunzip -N {{ chisel_release_linux.name }}"
    chdir: "{{ tools_root_path }}/chisel/"
  become: true

# --- Windows ---

- name: Select chisel Windows artifact
  set_fact:
    chisel_release_windows: "{{ (chisel_release.json.assets | selectattr('name', 'match', '.*_windows_amd64.gz' ))[0] }}"

- name: Download Windows artifact
  ansible.builtin.get_url:
    url:  "{{ chisel_release_windows.browser_download_url }}"
    dest: "{{ tools_root_path }}/chisel/{{ chisel_release_windows.name }}"
  become: true

# unarchive do not support *.gz
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html#notes
- name: Extract content
  ansible.builtin.command:
    cmd: "gunzip -N {{ chisel_release_windows.name }}"
    chdir: "{{ tools_root_path }}/chisel/"
  become: true

