---

- name: "Install pipx tools"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
  loop:
    - { name: 'updog', url: 'git+https://github.com/sc0tfree/updog.git' }

