---
# tasks file for microsoft-vscode

#- name: "[MS VSCode] Remove vscodium"
#  become: true
#  apt:
#    name: 
#    - vscodium
#    - codium
#    state: absent
#    autoremove: yes

#- name: "[MS VSCode] Include Setup Microsoft repository"
#  include_tasks: install-vscode-msrepo.yml

- name: "[MS VSCode] Include Setup Microsoft repository"
  include_tasks: install-vscode.yml

- name: "[MS VSCode] Include Setup user config"
  include_tasks: user-ms_vscode.yml


#- name: "[MS VSCode] Include Codium"
#  include_tasks: install-vscodium.yml

#- name: "[MS VSCode] Include Setup user config Codium"
#  include_tasks: user-ms_vscodium.yml
