---

# references :
# https://code.visualstudio.com/docs/setup/linux
# https://wiki.debian.org/VisualStudioCode

- name:  Install apt https transport tools
  become: true
  apt:
    name: 
    - gnupg
    - apt-transport-https
    state: present
    autoremove: yes
    

- name: Download and Add Microsoft Key to Apt-Get Keyring
  become: true
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: "[APT MS] add MS repo"
  become: true
  ansible.builtin.copy:
    src: microsoft.list
    dest: /etc/apt/sources.list.d/microsoft.list
    owner: root
    group: root
    mode: "0644"
  when: ansible_os_family == "Parrot OS"
  tags:
  - apt

#- name: Remove Microsoft Repository from /etc/apt/sources.list.d (temporary)
#  become: true
#  file:
#    path: /etc/apt/sources.list.d/microsoft.list
#    state:    absent

- name: "[APT] Updates APT cache"
  become: true
  apt: 
    update_cache: yes


- name: "[APT] Install MS packages"
  become: true
  ansible.builtin.apt:
    name: code
    state: present


# Since this can cause conflicts, remove these repos.
- name: "[APT] Remove MS repo"
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: absent
  loop:
    - "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye main"
    - "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
    - "deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main"


- name: "[APT] Updates APT cache"
  become: true
  apt: 
    update_cache: yes
