---

- name: "[MS VSCode:user] Create user folders"
  # become: yes
  # become_user: kali
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - "{{ ansible_user_dir }}/.config/Code/"
    - "{{ ansible_user_dir }}/.config/Code/User"

- name: "[MS VSCode:user] Copy user config file"
  # become: yes
  # become_user: kali
  copy:
    src: user-vscode-settings.json
    dest: "{{ ansible_user_dir }}/.config/Code/User/settings.json"
    mode: '0644'
    force: no

- name: "[MS VSCode:user] user config"
  # become: yes
  # become_user: kali
  command: code --install-extension "{{ item }}"
  loop: "{{ vscode_extensions }}"

