---

- name: "[MS VSCode:user] Create user folders"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - "{{ ansible_user_dir }}/.config/Code/"
    - "{{ ansible_user_dir }}/.config/Code/User"
    - "{{ ansible_user_dir }}/.config/Code/User/snippets"

- name: "[MS VSCode:user] Copy user config file"
  copy:
    src: user-vscode-settings.json
    dest: "{{ ansible_user_dir }}/.config/Code/User/settings.json"
    mode: '0644'
    force: no

- name: "[MS VSCode:user] Copy user config file: markdown snippets"
  copy:
    src: markdown.json
    dest: "{{ ansible_user_dir }}/.config/Code/User/snippets/markdown.json"
    mode: '0644'
    force: no

- name: "[MS VSCode:user] user config"
  command: code --install-extension "{{ item }}"
  loop: "{{ vscode_extensions }}"
