---
# tasks file for k8s-clients

- name: Install argocd CLI
  ansible.builtin.include_tasks: argocd.yaml

- name: Install helm CLI
  ansible.builtin.include_tasks: helm.yaml

- name: Install kubectl CLI
  ansible.builtin.include_tasks: kubectl.yaml
