---
# tasks file for tool-chisel

- name: "[Exegol:chisel] Clean directory"
  become: true
  ansible.builtin.file:
    path: "{{ exegol.my_resources }}/chisel/"
    state: absent

# ---------------------------------------------------------

- name: "[Exegol:chisel] Win64:Create directory if it does not exist"
  ansible.builtin.file:
    path: "{{ exegol.my_resources }}/chisel/windows_amd64"
    state: directory
    mode: '0755'
    recurse: yes

- name: "[Exegol:chisel] Win64: Download"
  ansible.builtin.get_url:
    url: "https://github.com/jpillora/chisel/releases/download/v{{ _chisel_version }}/chisel_{{ _chisel_version }}_windows_amd64.gz"
    dest: "{{ exegol.my_resources }}/chisel/windows_amd64/chisel_windows_amd64.gz"
    mode: '0444'

- name: "[chisel-win64] Extract"
  ansible.builtin.command:
    cmd: "gunzip {{ exegol.my_resources }}/chisel/windows_amd64/chisel_windows_amd64.gz"

# ---------------------------------------------------------

- name: "[Exegol:chisel] Lin64: Create directory if it does not exist"
  ansible.builtin.file:
    path: "{{ exegol.my_resources }}/chisel/linux_amd64"
    state: directory
    mode: '0755'

- name: "[Exegol:chisel] Lin64: Download"
  ansible.builtin.get_url:
    url: "https://github.com/jpillora/chisel/releases/download/v{{ _chisel_version }}/chisel_{{ _chisel_version }}_linux_amd64.gz"
    dest: "{{ exegol.my_resources }}/chisel/linux_amd64/chisel_linux_amd64.gz"
    mode: '0444'

- name: "[Exegol:chisel] Lin64: Extract"
  ansible.builtin.command:
    cmd: "gunzip {{ exegol.my_resources }}/chisel/linux_amd64/chisel_linux_amd64.gz"
