---
# tasks file for k8s-clients

- name: Install kubectl
  ansible.builtin.import_role:
    name: kube_cloud.general.kubectl
  become: true

# other way is by installing via apt
# - name: "Installing Packages"
#   package:
#     name:
#       - kubernetes-client
#       # - kubernetes-helm
#     state: latest
#   become: true

- name: Install helm
  ansible.builtin.import_role:
    name: kube_cloud.general.helm
  become: true
