---
# tasks file for redteam-exploit

- ansible.builtin.include_tasks: chisel.yaml
- ansible.builtin.include_tasks: crackmap.yaml
- ansible.builtin.include_tasks: dictionaries.yml
- ansible.builtin.include_tasks: fix-samba.yml
- ansible.builtin.include_tasks: impacket.yaml
- ansible.builtin.include_tasks: runascs.yaml
- ansible.builtin.include_tasks: sharpcollection.yaml
- ansible.builtin.include_tasks: updog.yaml

# Exploit-DB
- name: "Installing Exploit-db"
  package:
    name:
      - exploitdb
    state: latest
  become: true



- name: "Installing evil-winrm"
  package:
    name:
      - evil-winrm
    state: latest
  become: true



- name: "Installing misc packages for exploitation"
  package:
    name:
      - rlwrap
      - netcat-traditional
    state: latest
  become: true




# - name: "Installing tools from Gems"
#   gem:
#     name: "{{ item }}"
#     state: latest
#   loop:
#     - logger
#     - stringio
#     - winrm
#     - builder
#     - erubi
#     - gssapi
#     - gyoku
#     - httpclient
#     - logging
#     - little-plugger
#     - nori
#     - rubyntlm
#     - winrm-fs
#     #- evil-winrm
#   become: true