---

- name: "clean directories"
  ansible.builtin.file:
    path: "{{ resources_root_path }}/RunAsCS"
    state: absent
  become: true

- name: "create directories"
  ansible.builtin.file:
    path: "{{ resources_root_path }}/RunAsCS"
    state: directory
    mode: '0755'
  become: true

- name: Get RunAsCS latest tag
  uri:
    url: https://api.github.com/repos/antonioCoco/RunasCs/releases/latest
    return_content: true
  register: runascs_release

- name: Latest release
  ansible.builtin.debug:
    msg: "RunAsCS version: {{ runascs_release.json.name }}"



- name: Select RunAsCS artifact
  set_fact:
    runascs_release_zip: "{{ (runascs_release.json.assets | selectattr('name', 'match', 'RunasCs.zip' ))[0] }}"

- name: Download and extract
  ansible.builtin.unarchive:
    remote_src: yes 
    src: "{{ runascs_release_zip.browser_download_url }}"
    dest: "{{ resources_root_path }}/RunAsCS/"
  become: true

