---
- name: "locale > Ensure localisation files for '{{ locale.system }}' are available"
  become: true
  locale_gen:
    name: "{{ locale.system }}"
    state: present

- name: "locale > Ensure localisation files for '{{ locale.system_language }}' are available"
  become: true
  locale_gen:
    name: "{{ locale.system_language }}"
    state: present

- name: "locale > Get current locale and language configuration"
  command: localectl status
  register: locale_status
  changed_when: false

- name: "locale > Parse 'LANG' from current locale and language configuration"
  set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') }}"

- name: "locale > Parse 'LANGUAGE' from current locale and language configuration"
  set_fact:
    locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

- name: "locale > Configure locale to '{{ locale.system }}' and language to '{{ locale.system_language }}'"
  become: true
  command: localectl set-locale LANG={{ locale.system }} LANGUAGE={{ locale.system_language }}
  changed_when: locale_lang != locale.system or locale_language != locale.system_language

# tasks file for keyboard_configuration
- name: "locale > install package for keyboard layout"
  become: true
  apt:
    name: keyboard-configuration
    state: present

- name: "locale > Set Keyboard layout"
  become: true
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^.*XKBLAYOUT.*'
    line: 'XKBLAYOUT="{{ locale.keyboard_layout }}"'
    state: present

- name: "locale > Set timezone"
  become: true
  timezone:
    name: "{{ locale.timezone }}"
