---
# tasks file for docker

- name: "[Docker] Install packages"
  become: true
  apt:
    name: 
    - docker
    - docker.io
    - docker-compose
    state: present

- name: "[Docker] Allow user to access docker"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

# Since groups have changed, we need to log out and re-login to take groups into account

- name: Reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta:
    reset_connection

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started
  become: true
