---
# tasks file for docker

- name: "[Docker] Install packages"
  become: true
  apt:
    name: 
    - docker
    - docker.io
    - docker-compose
    state: present

- name: "[Docker] Allow user to access docker"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

