---

- name: "apt > install system packages"
  become: true
  apt:
    name: 
      - glances
      - jq
      #- flameshot
      #- exiftool
      - btop                # system monitor : https://github.com/aristocratos/btop
      #- ranger # console file-manager
      #- rdate   # date time fix
      #- ntpdate
      - python3
      - virtualenv  # python
      - pipx
      - curl
      - wget
    state: "present"

