---

- name: "ufw > Install"
  become: true
  apt:
    name: "rsyslog"
    state: "latest"
  tags:
    - updatedb

- name: "ufw > Enable rsyslog service"
  service:
    name: rsyslog
    enabled: yes
    state: started
  become: true


- name: "ufw > Configure UFW"
  ufw:
    state: enabled
    policy: allow
  become: true


- name: "ufw > Log SYN packets in INPUT Chain"
  lineinfile:
    path: /etc/ufw/after.rules
    line: '-A ufw-after-input -p tcp --syn -j LOG --log-prefix "[UFW-SYN-LOG] "'
    insertbefore: "# don't delete the 'COMMIT' line or these rules won't be processed"
  become: true

  
- name: "ufw > Restart ufw"
  service:
    name: ufw
    state: restarted
  become: true

        

