---

- name: Check if cluster {{ cluster_name }} is running
  shell: "kind get clusters | grep -w {{ cluster_name }}"
  failed_when: false
  register: cluster_list

- name: Delete kind cluster {{ cluster_name }}
  shell: "kind delete cluster --name {{ cluster_name }}"
  when: cluster_list.stdout | length > 0
  